name: Bump version
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Bump version and push tag
      uses: Eloston/ungoogled-chromium@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
